"""Add scan options

Revision ID: e170b33fcda1
Revises: 20260710_0001
Create Date: 2026-07-26 20:10:12.993074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e170b33fcda1'
down_revision: Union[str, Sequence[str], None] = '20260710_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('options', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'options')
    # ### end Alembic commands ###
